version: "3.9"
services:
  person:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "rootpwd"
    ports:
    - "5432:5432"
